// import React from "react";
// import PieChartComponent from "./PieChartComponent";
// import "../assets/css/CarbonFootprintContent.css";

// const CarbonFootprintContent: React.FC = () => {
//   return (
//     <div className="carbon-footprint">
//       <div className="header">
//         <h2>Carbon footprint</h2>
//         <p>CO2 footprint generated by the battery</p>
//       </div>
//       <hr />
//       <div className="carbon-details">
//         <div className="carbon-item">
//           <p className="carbon-label">
//             Amount<span className="verified-badge2">Verified</span>
//           </p>
//           <p>137.00gCO₂e/kWh</p>
//         </div>
//         <div className="carbon-item">
//           <PieChartComponent />
//         </div>
//         <div className="carbon-item">
//           <p className="carbon-label">Performance class</p>
//           <p>B</p>
//         </div>
//         <div className="carbon-item">
//           <p className="carbon-label">CO2 study reference</p>
//           <a href="#" className="carbon-link">
//             External link <span className="link-icon">🔗</span>
//           </a>
//         </div>
//       </div>
//     </div>
//   );
// };

// export default CarbonFootprintContent;




import React from "react";
import PieChartComponent from "./PieChartComponent";

const CarbonFootprintContent: React.FC = () => {
  return (
    <div className="p-4">
      <div className="mb-2">
        <h2 className="text-base text-black">Carbon footprint</h2>
        <p className="text-base">CO2 footprint generated by the battery</p>
      </div>
      <hr className="border-gray-300" />
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-2 mt-2">
        <div className="p-2">
          <p className="font-bold mb-1 text-gray-600">
            Amount
            <span className="bg-green-500 text-white py-1 px-2 rounded-full text-sm font-bold ml-1">Verified</span>
          </p>
          <p className="font-bold">137.00gCO₂e/kWh</p>
        </div>
        <div className="p-2">
          <PieChartComponent />
        </div>
        <div className="p-2">
          <p className="font-bold mb-1 text-gray-600">Performance class</p>
          <p className="font-bold">B</p>
        </div>
        <div className="p-2">
          <p className="font-bold mb-1 text-gray-600">CO2 study reference</p>
          <a 
            href="#" 
            className="text-green-500 text-base hover:underline"
          >
            External link <span className="text-sm ml-1">🔗</span>
          </a>
        </div>
      </div>
    </div>
  );
};

export default CarbonFootprintContent;